export interface Product {
  id: string;
  name: string;
  price: number;
  images: string[];
  category: "MOSI" | "Everyday" | "Limited";
  description: string;
  sizes: string[];
  colors: string[];
}

export const COLOR_SWATCHES: Record<string, string> = {
  Black: "#1a1a1a",
  Ochre: "#c8963c",
  Terracotta: "#b4533a",
  Indigo: "#2b3a67",
  Ivory: "#f1e9da",
};

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Heritage Wrap",
    price: 89.99,
    category: "MOSI",
    images: ["/bybakari/photoshoot/IMG_4681.webp", "/bybakari/photoshoot/IMG_4702.webp", "/bybakari/photoshoot/IMG_4689.webp"],
    description: "A contemporary wrap celebrating Zimbabwean textile traditions. Perfect for layering and versatile styling. As seen in our MOSI campaign.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ochre", "Black", "Indigo"],
  },
  {
    id: "2",
    name: "Modern Dress",
    price: 129.99,
    category: "MOSI",
    images: ["/bybakari/photoshoot/IMG_4867.webp", "/bybakari/photoshoot/IMG_4884.webp", "/bybakari/photoshoot/IMG_4879.webp"],
    description: "A sleek silhouette featuring the MOSI print. Effortlessly elegant for any occasion. Featured in our photoshoot campaign.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ochre", "Black", "Indigo"],
  },
  {
    id: "3",
    name: "Classic Coat",
    price: 199.99,
    category: "MOSI",
    images: ["/bybakari/photoshoot/IMG_4947.webp", "/bybakari/photoshoot/IMG_4935.webp", "/bybakari/photoshoot/IMG_4924.webp"],
    description: "A tailored coat in MOSI print. Sculptural and commanding, perfect for making a statement. Captured in our campaign shoot.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ochre", "Black", "Indigo"],
  },
  {
    id: "4",
    name: "Cultural Piece",
    price: 149.99,
    category: "MOSI",
    images: ["/bybakari/photoshoot/IMG_4808.webp", "/bybakari/photoshoot/IMG_4807.webp", "/bybakari/photoshoot/IMG_4801.webp"],
    description: "A bold statement piece celebrating African artistry. Wear it proud. From our latest photoshoot.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ochre", "Black", "Indigo"],
  },
  {
    id: "5",
    name: "Signature Collection",
    price: 179.99,
    category: "MOSI",
    images: ["/bybakari/photoshoot/IMG_4735.webp", "/bybakari/photoshoot/IMG_4736.webp", "/bybakari/photoshoot/IMG_4727.webp"],
    description: "The signature MOSI piece that started it all. Timeless and unforgettable. See it styled in our campaign.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ochre", "Black", "Indigo"],
  },
  {
    id: "6",
    name: "Artisan Garment",
    price: 99.99,
    category: "Everyday",
    images: ["/bybakari/Highlights/_TBJ0539.webp", "/bybakari/Highlights/_TBJ0730.webp"],
    description: "A hand-crafted everyday essential. Comfortable, durable, and beautifully detailed.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Terracotta"],
  },
  {
    id: "7",
    name: "Elegant Style",
    price: 169.99,
    category: "Everyday",
    images: ["/bybakari/Highlights/_TBJ0730.webp", "/bybakari/Highlights/_TBJ0718.webp"],
    description: "Understated elegance meets cultural pride. A versatile piece for everyday wear.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Terracotta"],
  },
  {
    id: "8",
    name: "Premium Piece",
    price: 189.99,
    category: "Everyday",
    images: ["/bybakari/Highlights/_TBJ0718.webp", "/bybakari/Highlights/_TBJ0677.webp"],
    description: "Premium craftsmanship in every stitch. A piece designed to last.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Terracotta"],
  },
  {
    id: "9",
    name: "Unique Design",
    price: 139.99,
    category: "Everyday",
    images: ["/bybakari/Highlights/_TBJ0677.webp", "/bybakari/Highlights/_TBJ0532.webp"],
    description: "A one-of-a-kind design from our exclusive collaborations with local artisans.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Terracotta"],
  },
  {
    id: "10",
    name: "Bespoke Collection",
    price: 219.99,
    category: "Everyday",
    images: ["/bybakari/Highlights/_TBJ0532.webp", "/bybakari/Highlights/_TBJ0604.webp"],
    description: "Custom-made exclusivity. Limited availability, endless style.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Terracotta"],
  },
  {
    id: "11",
    name: "Limited Edition Vest",
    price: 159.99,
    category: "Limited",
    images: ["/bybakari/Highlights/_TBJ0593.webp", "/bybakari/Highlights/_TBJ0593.webp"],
    description: "A rare limited-run piece. Only 50 units produced globally.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Indigo", "Ochre", "Ivory"],
  },
  {
    id: "12",
    name: "Exclusive Jacket",
    price: 249.99,
    category: "Limited",
    images: ["/bybakari/Highlights/_TBJ0595(2).webp", "/bybakari/Highlights/_TBJ0595(2).webp"],
    description: "Hand-finished in Zimbabwe. A collector's piece of contemporary African fashion.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Indigo", "Ochre", "Ivory"],
  },
  {
    id: "13",
    name: "Artisan Collaboration",
    price: 189.99,
    category: "Limited",
    images: ["/bybakari/Highlights/_TBJ0661(2).webp", "/bybakari/Highlights/_TBJ0661(2).webp"],
    description: "Co-created with a legendary Zimbabwean textile artist. Museum-quality craftsmanship.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Indigo", "Ochre", "Ivory"],
  },
  {
    id: "14",
    name: "Ceremonial Wear",
    price: 279.99,
    category: "Limited",
    images: ["/bybakari/Highlights/_TBJ0730.webp", "/bybakari/Highlights/_TBJ0714.webp"],
    description: "Inspired by ceremonial traditions. Perfect for special moments.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Indigo", "Ochre", "Ivory"],
  },
  {
    id: "15",
    name: "Heritage Scarf",
    price: 79.99,
    category: "Limited",
    images: ["/bybakari/Highlights/_TBJ0718.webp", "/bybakari/Highlights/_TBJ0677.webp"],
    description: "Woven from rare natural fibers. An accessory that tells a thousand stories.",
    sizes: ["One Size"],
    colors: ["Indigo", "Ochre", "Ivory"],
  },
  {
    id: "16",
    name: "Studio Edition",
    price: 199.99,
    category: "Limited",
    images: ["/bybakari/Highlights/_TBJ0532.webp", "/bybakari/Highlights/_TBJ0604.webp"],
    description: "Direct from our Harare studio. Each piece numbered and authenticated.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Indigo", "Ochre", "Ivory"],
  },
  {
    id: "17",
    name: "Signature Blouse",
    price: 119.99,
    category: "Everyday",
    images: ["/bybakari/Highlights/_TBJ0539.webp", "/bybakari/Highlights/_TBJ0730.webp"],
    description: "A timeless blouse that pairs with everything. Modern and sophisticated.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Terracotta"],
  },
  {
    id: "18",
    name: "Tailored Trousers",
    price: 139.99,
    category: "Everyday",
    images: ["/bybakari/Highlights/_TBJ0718.webp", "/bybakari/Highlights/_TBJ0677.webp"],
    description: "Precision tailoring meets comfort. The foundation of any great wardrobe.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Terracotta"],
  },
  {
    id: "19",
    name: "Maxi Skirt",
    price: 149.99,
    category: "MOSI",
    images: ["/bybakari/Highlights/_TBJ0532.webp", "/bybakari/Highlights/_TBJ0604.webp"],
    description: "Flowing elegance in MOSI print. Celebrate movement and grace.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ochre", "Black", "Indigo"],
  },
  {
    id: "20",
    name: "Oversized Shirt",
    price: 129.99,
    category: "Everyday",
    images: ["/bybakari/Highlights/_TBJ0587(2).webp", "/bybakari/Highlights/_TBJ0708.webp"],
    description: "Relaxed fit, premium fabric. Perfect for casual days and formal nights.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory", "Terracotta"],
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getRelatedProducts(productId: string, category: string, limit: number = 3): Product[] {
  return PRODUCTS.filter((p) => p.category === category && p.id !== productId).slice(0, limit);
}
