/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrintRouteImport } from './routes/print'
import { Route as PhotoshootRouteImport } from './routes/photoshoot'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopProductIdRouteImport } from './routes/shop_.$productId'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as ApiPaynowResultRouteImport } from './routes/api.paynow-result'
import { Route as ApiPaymentStatusRouteImport } from './routes/api.payment-status'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoshootRoute = PhotoshootRouteImport.update({
  id: '/photoshoot',
  path: '/photoshoot',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop_/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaynowResultRoute = ApiPaynowResultRouteImport.update({
  id: '/api/paynow-result',
  path: '/api/paynow-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentStatusRoute = ApiPaymentStatusRouteImport.update({
  id: '/api/payment-status',
  path: '/api/payment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/photoshoot': typeof PhotoshootRoute
  '/print': typeof PrintRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/paynow-result': typeof ApiPaynowResultRoute
  '/payment/return': typeof PaymentReturnRoute
  '/shop/$productId': typeof ShopProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/photoshoot': typeof PhotoshootRoute
  '/print': typeof PrintRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/paynow-result': typeof ApiPaynowResultRoute
  '/payment/return': typeof PaymentReturnRoute
  '/shop/$productId': typeof ShopProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/photoshoot': typeof PhotoshootRoute
  '/print': typeof PrintRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/paynow-result': typeof ApiPaynowResultRoute
  '/payment/return': typeof PaymentReturnRoute
  '/shop_/$productId': typeof ShopProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/lookbook'
    | '/photoshoot'
    | '/print'
    | '/shop'
    | '/sitemap.xml'
    | '/story'
    | '/api/chat'
    | '/api/checkout'
    | '/api/payment-status'
    | '/api/paynow-result'
    | '/payment/return'
    | '/shop/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/lookbook'
    | '/photoshoot'
    | '/print'
    | '/shop'
    | '/sitemap.xml'
    | '/story'
    | '/api/chat'
    | '/api/checkout'
    | '/api/payment-status'
    | '/api/paynow-result'
    | '/payment/return'
    | '/shop/$productId'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/lookbook'
    | '/photoshoot'
    | '/print'
    | '/shop'
    | '/sitemap.xml'
    | '/story'
    | '/api/chat'
    | '/api/checkout'
    | '/api/payment-status'
    | '/api/paynow-result'
    | '/payment/return'
    | '/shop_/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LookbookRoute: typeof LookbookRoute
  PhotoshootRoute: typeof PhotoshootRoute
  PrintRoute: typeof PrintRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiPaymentStatusRoute: typeof ApiPaymentStatusRoute
  ApiPaynowResultRoute: typeof ApiPaynowResultRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photoshoot': {
      id: '/photoshoot'
      path: '/photoshoot'
      fullPath: '/photoshoot'
      preLoaderRoute: typeof PhotoshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop_/$productId': {
      id: '/shop_/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paynow-result': {
      id: '/api/paynow-result'
      path: '/api/paynow-result'
      fullPath: '/api/paynow-result'
      preLoaderRoute: typeof ApiPaynowResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-status': {
      id: '/api/payment-status'
      path: '/api/payment-status'
      fullPath: '/api/payment-status'
      preLoaderRoute: typeof ApiPaymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LookbookRoute: LookbookRoute,
  PhotoshootRoute: PhotoshootRoute,
  PrintRoute: PrintRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiPaymentStatusRoute: ApiPaymentStatusRoute,
  ApiPaynowResultRoute: ApiPaynowResultRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
